// Copyright (c) 2024-2026 Az-FIRST
// http://github.com/AZ-First
// Copyright (c) 2021-2026 Littleton Robotics
// http://github.com/Mechanical-Advantage
//
// Use of this source code is governed by a BSD
// license that can be found in the AdvantageKit-License.md file
// at the root directory of this project.

package frc.robot.subsystems.vision;

import edu.wpi.first.math.geometry.Pose3d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Set;
import org.littletonrobotics.junction.AutoLog;

public interface VisionIO {
  @AutoLog
  class VisionIOInputs {
    public boolean connected = false;

    /** Latest "camera to target" observation (optional) */
    public TargetObservation latestTargetObservation =
        new TargetObservation(Rotation2d.kZero, Rotation2d.kZero);

    /** Pose observations generated by the camera pipeline (each has its own timestamp) */
    public PoseObservation[] poseObservations = new PoseObservation[0];

    /** Union of tag IDs seen this loop (for logging/UI only) */
    public int[] tagIds = new int[0];
  }

  /** Represents the angle to a simple target, not used for pose estimation. */
  record TargetObservation(Rotation2d tx, Rotation2d ty) {}

  /** Represents a robot pose sample used for pose estimation. */
  record PoseObservation(
      double timestamp, // camera capture time (seconds, same timebase as FPGA)
      Pose3d pose, // field->robot pose
      double ambiguity, // single-tag ambiguity if available
      int tagCount,
      double averageTagDistance,
      PoseObservationType type,
      Set<Integer> usedTagIds // immutable per observation
      ) {}

  enum PoseObservationType {
    MEGATAG_1,
    MEGATAG_2,
    PHOTONVISION
  }

  default void updateInputs(VisionIOInputs inputs) {}
}
